version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork
    ports:
      - "3000:3000"

networks:
  mynetwork:
    driver: bridge